name: YoggiesSMP
version: '${project.version}'
main: shwendel.yoggiessmp.YoggiesSMP
api-version: 1.20
commands:
  setshrine:
    description: Set the shrine location
  setspawn:
    description: Set the spawn location
  test:
    description: Testing command
  fragments:
    aliases: [ fragment ]
    description: Salvage items for Yoggies Fragments
  giveenchantment:
    aliases: [ giveenchant ]
    description: Give an enchantment to a player